force-app/main/default/objects/Breed__c/Breed__c.object-meta.xml
<CustomObject>
    <label>Breed</label>
    <nameField>
        <label>Breed Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Breeds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Breed__c/fields/Barking_Level__c.field-meta.xml
<CustomField>
    <fullName>Barking_Level__c</fullName>
    <label>Barking Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Only To Alert</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Very Vocal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Breed__c/fields/Coat_Length__c.field-meta.xml
<CustomField>
    <fullName>Coat_Length__c</fullName>
    <label>Coat Length</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Short</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Long</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Breed__c/fields/Coat_Type__c.field-meta.xml
<CustomField>
    <fullName>Coat_Type__c</fullName>
    <label>Coat Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wiry</fullName>
            </value>
            <value>
                <fullName>Rough</fullName>
            </value>
            <value>
                <fullName>Curly</fullName>
            </value>
            <value>
                <fullName>Hairless</fullName>
            </value>
            <value>
                <fullName>Corded</fullName>
            </value>
            <value>
                <fullName>Wavy</fullName>
            </value>
            <value>
                <fullName>Smooth</fullName>
            </value>
            <value>
                <fullName>Double</fullName>
            </value>
            <value>
                <fullName>Silky</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Breed__c/fields/Energy_Level__c.field-meta.xml
<CustomField>
    <fullName>Energy_Level__c</fullName>
    <label>Energy Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Couch Potato</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High Energy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Breed__c/fields/Good_With_Kids__c.field-meta.xml
<CustomField>
    <fullName>Good_With_Kids__c</fullName>
    <label>Good With Children</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Recommended</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Good With Children</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Breed__c/fields/Good_With_Other_Dogs__c.field-meta.xml
<CustomField>
    <fullName>Good_With_Other_Dogs__c</fullName>
    <label>Good With Other Dogs</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Recommended</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Good With Other Dogs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Breed__c/fields/Life_Expectancy__c.field-meta.xml
<CustomField>
    <fullName>Life_Expectancy__c</fullName>
    <label>Life Expectancy</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Breed__c/fields/Trainability_Level__c.field-meta.xml
<CustomField>
    <fullName>Trainability_Level__c</fullName>
    <label>Trainability Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Self-Willed</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Eager To Please</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Breed_CC_Test.cls
@isTest
private with sharing class Breed_CC_Test {
    
    @isTest
    static void testCreateBreedPage(){
        PageReference Page = Page.CreateBreedPage;
        Test.setCurrentPage(Page);           
        Test.startTest();
        Breed_CC breed = new Breed_CC();
        String url = breed.createBreedPage().getURL();
        Test.stopTest();
    }

    @isTest
    static void testBreedPage(){
        PageReference Page = Page.BreedPage;
        Test.setCurrentPage(Page);           
        Test.startTest();
        Breed_CC breed = new Breed_CC();
        String url = breed.breedPage().getURL();
        Test.stopTest();
    }

    @isTest
    static void testSaveBreed(){
        PageReference Page = Page.CreateBreedPage;
        Test.setCurrentPage(Page);           
        Test.startTest();
        Breed_CC breed = new Breed_CC();
        String url = breed.saveBreed().getURL();
        Test.stopTest();
    }
   
   
   
   /*
    @TestSetup
   static void testData(){
        List<Breed__c> breedTestList = new List<Breed__c>();   
        for(Breed__c b : [SELECT Name, Barking_Level__c, Coat_Length__c, Coat_Type__c, Energy_Level__c,
                            Good_With_Kids__c, Good_With_Other_Dogs__c, Height__c, Life_Expectancy__c,
                            Trainability_Level__c, Weight__c FROM Breed__c]){
            breedTestList.add(b);
        }
    }
  

    @isTest
    static void testNavigation(){
        PageReference breedPage = Page.breedPage;
        Test.setCurrentPage(breedPage);
        
        Test.startTest();
        
        Breed_CC b = new Breed_CC();


        Test.stopTest();

    }
*/

    
}