force-app/main/default/objects/Breed__c/Breed__c.object-meta.xml
<CustomObject>
    <label>Breed</label>
    <nameField>
        <label>Breed Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Breeds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Family__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Street Address</description>
    <inlineHelpText>Street Address</inlineHelpText>
    <label>Address</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Family__c/fields/e_Mail__c.field-meta.xml
<CustomField>
    <fullName>e_Mail__c</fullName>
    <label>e-Mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Family__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Family__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pet__c/Pet__c.object-meta.xml
<CustomObject>
    <label>Pet</label>
    <nameField>
        <label>Pet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pet__c/fields/Breed__c.field-meta.xml
<CustomField>
    <fullName>Breed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Breed</label>
    <referenceTo>Breed__c</referenceTo>
    <relationshipLabel>Pets</relationshipLabel>
    <relationshipName>Pets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pet__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>300</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Pet__c/fields/Shelter__c.field-meta.xml
<CustomField>
    <fullName>Shelter__c</fullName>
    <label>Shelter</label>
    <referenceTo>Shelter__c</referenceTo>
    <relationshipLabel>Pets</relationshipLabel>
    <relationshipName>Pets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Shelter</fullName>
            </value>
            <value>
                <fullName>Adopted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pet_Adopted__c/Pet_Adopted__c.object-meta.xml
<CustomObject>
    <label>Pet Adopted</label>
    <nameField>
        <displayFormat>Pet-{0000}</displayFormat>
        <label>Pet Adopted Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pets Adopted</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pet_Adopted__c/fields/Family_Name__c.field-meta.xml
<CustomField>
    <fullName>Family_Name__c</fullName>
    <label>Family Name</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Pets Adopted</relationshipLabel>
    <relationshipName>Pets_Adopted</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pet_Adopted__c/fields/Pet_Name__c.field-meta.xml
<CustomField>
    <fullName>Pet_Name__c</fullName>
    <label>Pet Name</label>
    <referenceTo>Pet__c</referenceTo>
    <relationshipLabel>Pets Adopted</relationshipLabel>
    <relationshipName>Pets_Adopted</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pet_Adopted__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shelter__c/Shelter__c.object-meta.xml
<CustomObject>
    <label>Shelter</label>
    <nameField>
        <label>Shelter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shelters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shelter__c/fields/Address_2__c.field-meta.xml
<CustomField>
    <fullName>Address_2__c</fullName>
    <description>Apartment, Suite.</description>
    <inlineHelpText>Apartment, Suite.</inlineHelpText>
    <label>Address 2</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shelter__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shelter__c/fields/telephone__c.field-meta.xml
<CustomField>
    <fullName>telephone__c</fullName>
    <label>Telephone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/AdoptionProcessPageTest.cls
@IsTest
public with sharing class AdoptionProcessPageTest {
    /*@TestSetup
    private static void makeData(){
        Pet__c pet = new Pet__c();
        ApexPages.StandardController stdcon = new Apexpages.StandardController(pet);
        AdoptionProcessCC controller = new AdoptionProcessCC(stdcon);

    }*/
    @isTest static void testSearch() {
        // Tests the search function of VF page
        Shelter__c newShelter = new Shelter__c(Name = 'Test Shelter', Capacity__c = 10, City__c = 'New City', State__c = 'MD', 
        Address__c = '123 Test Street', telephone__c = '1231231234', e_Mail__c = 'test@test.com', Zip_Code__c = '12345');
        insert newShelter;
        Breed__c testBreed = new Breed__c(Name = 'Testing Breed');
        insert testBreed;
        Pet__c pet = new Pet__c(Name = 'NewPet',Breed__c = testBreed.id, Status__c = 'In Shelter', Shelter__c = newShelter.id);
        insert pet;
        ApexPages.StandardController stdcon = new Apexpages.StandardController(pet);
        AdoptionProcessCC controller = new AdoptionProcessCC(stdcon);
        controller.searchText ='Testing Breed';
        controller.search();

        System.assertEquals(1, controller.searchResults.size(), 'Only should contain 1 result');
    }

    @isTest static void testSaveAdoptionRecords() {
        //Supposed to Test the saveAdoptionFunction
        Shelter__c newShelter = new Shelter__c(Name = 'Test Shelter', Capacity__c = 10, City__c = 'New City', State__c = 'MD', 
        Address__c = '123 Test Street', telephone__c = '1231231234', e_Mail__c = 'test@test.com', Zip_Code__c = '12345');
        insert newShelter;
        Breed__c testBreed2 = new Breed__c(Name = 'Testing Breed');
        insert testBreed2;
        Pet__c pet2 = new Pet__c(Name = 'NewPet',Breed__c = testBreed2.id, Status__c = 'In Shelter', Shelter__c = newShelter.id);
        insert pet2;
        Family__c newFam = new Family__c(Name= 'Carrion',Address__c='123 Jasmine St',Address_2__c='323',City__c='Florence',e_Mail__c='carrrion@example.com',Notes__c='',
        State__c='LA',Status__c='Pending Information',Telephone__c='7872256199',Zip_Code__c='35221');
        insert newFam;
        Pet_Adopted__c newAdoption = new Pet_Adopted__c(Pet_Name__c = pet2.id, Family_Name__c = newFam.id);
        ApexPages.StandardController stdcon = new Apexpages.StandardController(pet2);
        AdoptionProcessCC controller = new AdoptionProcessCC(stdcon);
        //controller.saveAdoption();
        /*Boolean bool = false;
        for(Pet_Adopted__c check : controller.adoptList) {
            if(pet.Name == check.Pet_Name__c) {
                bool = true;
                break;
            }
        }
        System.assert(!bool);*/
        

    }
}