force-app/main/default/objects/Donation__c/Donation__c.object-meta.xml
<CustomObject>
    <label>Donation</label>
    <nameField>
        <displayFormat>Donation-{0000}</displayFormat>
        <label>Donation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Donation__c/fields/Blankets_Needed__c.field-meta.xml
<CustomField>
    <fullName>Blankets_Needed__c</fullName>
    <formula>if(Inventory__r.Blankets_and_Towels__c &lt; 20,
   20 - Inventory__r.Blankets_and_Towels__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Blankets Needed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Blankets_to_Donate__c.field-meta.xml
<CustomField>
    <fullName>Blankets_to_Donate__c</fullName>
    <label>Blankets to Donate</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Chew_Toys__c.field-meta.xml
<CustomField>
    <fullName>Chew_Toys__c</fullName>
    <label>Toys to Donate</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Crates_Needed__c.field-meta.xml
<CustomField>
    <fullName>Crates_Needed__c</fullName>
    <formula>if(Inventory__r.Crates__c&lt; 20,
   20 - Inventory__r.Crates__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Crates Needed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Crates_to_Donate__c.field-meta.xml
<CustomField>
    <fullName>Crates_to_Donate__c</fullName>
    <label>Crates to Donate</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Food_Needed__c.field-meta.xml
<CustomField>
    <fullName>Food_Needed__c</fullName>
    <formula>if(Inventory__r.Food_Bag__c &lt; 50,
   50 -  Inventory__r.Food_Bag__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Food Needed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Food_to_Donate__c.field-meta.xml
<CustomField>
    <fullName>Food_to_Donate__c</fullName>
    <label>Food to Donate</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Leashes_Needed__c.field-meta.xml
<CustomField>
    <fullName>Leashes_Needed__c</fullName>
    <formula>if(Inventory__r.Leashes__c &lt; 40,
   40 -  Inventory__r.Leashes__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Leashes Needed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Leashes_to_Donate__c.field-meta.xml
<CustomField>
    <fullName>Leashes_to_Donate__c</fullName>
    <label>Leashes to Donate</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Towels_Needed__c.field-meta.xml
<CustomField>
    <fullName>Towels_Needed__c</fullName>
    <formula>if(Inventory__r.Paper_Towels__c &lt; 100,
   100 -  Inventory__r.Paper_Towels__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Towels Needed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Towels_to_Donate__c.field-meta.xml
<CustomField>
    <fullName>Towels_to_Donate__c</fullName>
    <label>Towels to Donate</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Toys_Needed__c.field-meta.xml
<CustomField>
    <fullName>Toys_Needed__c</fullName>
    <formula>if(Inventory__r.Chew_Toys__c &lt; 40,
   40 -  Inventory__r.Chew_Toys__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Toys Needed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Chew_Toys__c.field-meta.xml
<CustomField>
    <fullName>Chew_Toys__c</fullName>
    <label>Chew Toys</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DonationPage_Test.cls
@isTest
private class DonationPage_Test {
    @testSetup
    private static void testData() {
        List<Donation__c> donTestList = new List<Donation__c>();
        for (Donation__c don : [SELECT Name, id, Inventory__c, Blankets_Needed__c, Blankets_to_Donate__c, Crates_Needed__c, Crates_to_Donate__c, 
                                    Food_Needed__c, Food_to_Donate__c, Leashes_Needed__c, Leashes_to_Donate__c, Towels_Needed__c, Towels_to_Donate__c,
                                    Toys_Needed__c, Chew_Toys__c FROM Donation__c]) {
            
                donTestList.add(don);
            
        }
    }

    @isTest
    private static void testSearchCoursesNavigation(){
        PageReference availabelDonations = Page.AvailableDonations;
        Test.setCurrentPage(availabelDonations);

        //DonationPage_CC dp = new DonationPage_CC();

        Test.startTest();        
        // String url = availabelDonations.getURL();
        
        Test.stopTest();

        //System.assertEquals(Page.AvailableDonations.getURL(), url, 'ERROR: Expected to navigate to /apex/listcoursedeliveriespage');

    }
}