force-app/main/default/objects/Donation__c/Donation__c.object-meta.xml
<CustomObject>
    <label>Donation</label>
    <nameField>
        <displayFormat>Donation-{0000}</displayFormat>
        <label>Donation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Donation__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DonationPage_CC.cls
public with sharing class DonationPage_CC {
    
    private ApexPages.StandardController controller;
    public DonationPage_CC(ApexPages.StandardController controller){
        this.controller = controller;
    }
    
    public List<Donation__c> donList {
        get {
            if (donList == null) {
                donList = new List<Donation__c>();
                for (Donation__c don : [SELECT Name, id, Inventory__r.Name FROM Donation__c]) {
                    donList.add(don);
                }
            }
            return donList;
        }
        set;
    }

    public PageReference availablePage(){
        return Page.AvailableDonations;   
    }

    public PageReference goHomePage(){
        return Page.AvailableDonations;   
    }

}