force-app/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Family__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pet_Adopted__c/Pet_Adopted__c.object-meta.xml
<CustomObject>
    <label>Pet Adopted</label>
    <nameField>
        <displayFormat>Pet-{0000}</displayFormat>
        <label>Pet Adopted Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pets Adopted</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pet_Adopted__c/fields/Family_Name__c.field-meta.xml
<CustomField>
    <fullName>Family_Name__c</fullName>
    <label>Family Name</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Pets Adopted</relationshipLabel>
    <relationshipName>Pets_Adopted</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pet_Adopted__c/fields/Pet_Name__c.field-meta.xml
<CustomField>
    <fullName>Pet_Name__c</fullName>
    <label>Pet Name</label>
    <referenceTo>Pet__c</referenceTo>
    <relationshipLabel>Pets Adopted</relationshipLabel>
    <relationshipName>Pets_Adopted</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pet_Adopted__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Pet_AdoptedTriggerHandler.cls
public with sharing class Pet_AdoptedTriggerHandler {

    public static void preventInvalidPets(List<Pet_Adopted__c> newPetList,
                                                      Map<ID, Pet_Adopted__c> oldPetMap) {
        List<Id> allPets = new List<Id>();

        for (List<Pet_Adopted__c> pets : [SELECT Pet_Name__c FROM Pet_Adopted__c]) {
            for (Pet_Adopted__c p : pets) {
                allPets.add(p.Pet_Name__c);
            }
        }
        
        for (Pet_Adopted__c pet : newPetList) {
            Boolean checkName = (trigger.isInsert || 
            oldPetMap.get(pet.Id).Pet_Name__c != pet.Pet_Name__c);
            if (checkName && pet.Pet_Name__c != NULL) {
                if (allPets.contains(pet.Pet_Name__c)) {
                    pet.Pet_Name__c.addError(
                    'This Pet is already adopted.');
                }
            }
        }
    }

    public static void preventInvalidFamilies(List<Pet_Adopted__c> newPetList,
                                                      Map<ID, Pet_Adopted__c> oldPetMap) {
        List<Id> allFamilies = new List<Id>();

        for (List<Family__c> family : [SELECT Id FROM Family__c WHERE Status__c != 'Approved']) {
            for (Family__c f : family) {
                allFamilies.add(f.Id);
            }
        }
        
        for (Pet_Adopted__c fam : newPetList) {
            Boolean checkFamily = (trigger.isInsert || 
            oldPetMap.get(fam.Id).Family_Name__c != fam.Family_Name__c);
            if (checkFamily && fam.Family_Name__c != NULL) {
                if (allFamilies.contains(fam.Family_Name__c)) {
                    fam.Family_Name__c.addError(
                    'This family has pending information.');
                }
            }
        }
    }
}