force-app/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Family__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Street Address</description>
    <inlineHelpText>Street Address</inlineHelpText>
    <label>Address</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Family__c/fields/e_Mail__c.field-meta.xml
<CustomField>
    <fullName>e_Mail__c</fullName>
    <label>e-Mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Family__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Family__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NewFamilyControllerClass.cls
public with sharing class NewFamilyControllerClass {

     
        
        public Family__c newFam {get;set;}
        private final Family__c f;
    
        
    
        public NewFamilyControllerClass( ) {
    
            // newFam = [SELECT ID,Name,Address__c,Address_2__c,City__c,e_Mail__c,Notes__c,
            // State__c,Status__c,Telephone__c,Zip_Code__c
            //     FROM Family__c];

            
            newFam = new Family__c();
    
        }
     
    
        // public insertNewFamController(){
        //     newFam = new Family__c();
        // }
        // public PageReference MessageToHomePage(){
           
        //     PageReference pageR = new PageReference('http://www.google.com');

        //     return pageR;
           
            
            



        // }
        public  void testController(Family__c nF){

            this.newFam = nF;

            


        }

         
    
        public PageReference createNewFamily(){

            PageReference SuccessfulCreationMsgPage = null;

            List<Family__c> oldFamP = [SELECT Id,e_Mail__c, Telephone__c from Family__c]; 
             
            if(newFam.Name ==''|| newFam.Name==null){
                ApexPages.addMessage( new ApexPages.message(ApexPages.severity.ERROR, 'Please enter a Family name' ) );
    
             
            }
            else if(newFam.Telephone__c ==''|| newFam.Telephone__c==null){
    
               
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'You must enter an phone number'));
            }
            else if(newFam.e_Mail__c ==''|| newFam.e_Mail__c==null){
    
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'You must enter an email'));
    
    
    
    
            }
             else{

            Integer i = 0;
           
                
            for(Family__c f: oldFamP){
    
                if(newFam.Telephone__c == f.Telephone__c && newFam.id != f.id){

                    ApexPages.addMessage(new ApexPages.message( ApexPages.severity.ERROR,'This phone number is already in the system, try a different phone number'));
                   i= i+1;
                } 

                if(newFam.e_Mail__c == f.e_Mail__c && newFam.id != f.id){

                    ApexPages.addMessage(  new ApexPages.message(  ApexPages.severity.ERROR,  'This email is already in the system, try a different email'));
               i= i+1;
                } 

            
        }

            
             if(i<=0){
            insert newFam;
            ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM,'Your registration was Successfully!'));
                 }
            newFam = new Family__c();

             SuccessfulCreationMsgPage = Page.SuccessfulFamilyCreationPage;
            SuccessfulCreationMsgPage.setRedirect(true);
           
     
             }
             return SuccessfulCreationMsgPage;
    }

}