force-app/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Family__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Street Address</description>
    <inlineHelpText>Street Address</inlineHelpText>
    <label>Address</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Family__c/fields/e_Mail__c.field-meta.xml
<CustomField>
    <fullName>e_Mail__c</fullName>
    <label>e-Mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Family__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Family__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NewFamilyPage_Test.cls
@isTest
private  class NewFamilyPage_Test {


    


    @isTest static void testNewFamily(){
        // Succesful
        NewFamilyControllerClass  controller = new NewFamilyControllerClass ();    
        PageReference pageRef = Page.NewFamilyPage; 
        PageReference ref2= Page.SuccessfulFamilyCreationPage;
        Family__c newFam = new Family__c(Name= 'Carrion',Address__c='123 Jasmine St',Address_2__c='323',City__c='Florence',e_Mail__c='carrrion@example.com',Notes__c='',
        State__c='LA',Status__c='Pending Information',Telephone__c='7872256199',Zip_Code__c='35221'   );
        insert newFam;
         
        Test.setCurrentPage(PageRef);
        pageRef.getParameters().put('id',newFam.id);
         
        System.assertNotEquals(ref2,controller.createNewFamily());

         
        //NewFamilyControllerClass.testController(newFam);


    }
    @isTest static void testNewFamily2(){
        // fail null mail
    NewFamilyControllerClass  controller = new NewFamilyControllerClass ();   
    PageReference pageRef = Page.NewFamilyPage; 
    PageReference ref2= Page.SuccessfulFamilyCreationPage;
    Family__c newFam = new Family__c(Name='Hall',Address__c='123 John Latimer St',Address_2__c='323',City__c='Florence', Notes__c='',e_Mail__c= null,
    State__c='LA',Status__c='Pending Information',Telephone__c='7872250000',Zip_Code__c='35221'   );
    controller.testController(newFam);
     
    Test.setCurrentPage(PageRef);
    pageRef.getParameters().put('id',newFam.id);
     
    System.assertNotEquals(ref2,controller.createNewFamily());

   
    //NewFamilyControllerClass.testController(newFam);


}

@isTest static void testNewFamily3(){
        //fail null phone number
    NewFamilyControllerClass  controller = new NewFamilyControllerClass ();   
    PageReference pageRef = Page.NewFamilyPage; 
    Family__c newFam = new Family__c(Name='Bosh',Address__c='123 John Latimer St',Address_2__c='323',City__c='Florence',e_Mail__c='bosh@example.com',Notes__c='',
    State__c='LA',Status__c='Pending Information',Telephone__c='7872250001',Zip_Code__c='35221'   );
    
    controller.testController(newFam);
    Test.setCurrentPage(PageRef);
    pageRef.getParameters().put('id',newFam.id);
    
    System.assertNotEquals(null,controller.createNewFamily());

   
    //NewFamilyControllerClass.testController(newFam);


}
@isTest static void testNewFamily4(){
    //fail null same phoneNumber
NewFamilyControllerClass  controller = new NewFamilyControllerClass ();   
PageReference pageRef = Page.NewFamilyPage; 
Family__c newFam = new Family__c(Name='Jackson',Address__c='123 John Latimer St',Address_2__c='323',City__c='Florence',e_Mail__c='jack@example.com',Notes__c='',
State__c='LA',Status__c='Pending Information',Telephone__c='7876543122',Zip_Code__c='35221'   );

controller.testController(newFam);
Test.setCurrentPage(PageRef);
pageRef.getParameters().put('id',newFam.id);

System.assertNotEquals(null,controller.createNewFamily());


//NewFamilyControllerClass.testController(newFam);


}
    
     
     
}