force-app/main/default/objects/Pet__c/Pet__c.object-meta.xml
<CustomObject>
    <label>Pet</label>
    <nameField>
        <label>Pet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pet__c/fields/Last_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Last_Appointment__c</fullName>
    <label>Last Appointment</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pet__c/fields/Next_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Next_Appointment__c</fullName>
    <label>Next Appointment</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PetTriggerHandler.cls
public with sharing class PetTriggerHandler {
    public static void createNextAppointment(List<Pet__c> triggerNew) {
        
        List<Pet__c> nextApp = new List<Pet__c>();

            for (Pet__c p : triggerNew) {
                          
                p.Next_Appointment__c = p.Last_Appointment__c.addMonths(1);
                        
            }   
                 
        update nextApp;
    }
}